[build-system]
requires=["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name='torch4nlp'
version='0.0.8c5'
long_description = 'torch4nlp is a library for nlp based on torch'
authors = [
    {name="youngfoo", email="flyangovoyang@gmail.com"}
]
requires-python = ">=3.7"
