[build-system]
requires=["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name='torch4nlp'
version='0.0.8c4'
long_description_content_type="text/markdown"
long_description=README
authors = [
    {name="youngfoo", email="flyangovoyang@gmail.com"}
]
requires-python = ">=3.7"
