[build-system]
requires=["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name='torch4nlp'
version='0.0.9'
readme='README.md'
description = "My package description"
authors = [
    {name="youngfoo", email="flyangovoyang@gmail.com"}
]
requires-python = ">=3.7"
