file_parameters:
  delimeter: "	"
  fields:
    - name: text
      column: 0
      role: text
      tokenizer: bert
    - name: main_word
      column: 1
      role: label
      label_mapping: a.txt
      multilabel: False
    - name: attr
      column: 2
      role: label
      label_mapping: b.txt
      multilabel: True
      max_num: 8
